# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5ccc4e003c589c548158ad99ccf8ea0e563c83fad194a354182c43f90d15600c36578056bc2eb6ae8353442490ccd43ebb82f8a9d8a7c9e47c7b89fb4e1eda3

test:
  secret_key_base: db6bdf33bb28ca79aeca3ec233d4e4e6111bc504bf7cf1e632db53d92c5f3e2be265879e6af7b0cdd4462ab933e43103fb72dd8a3dcb82d56ee5b75fb0621667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
